name: Weekly Stats

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日的 UTC 00:00

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Aarebecca/stats@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
